spring.application.name=Mutualfund
server.port=9090
spring.datasource.url=jdbc:mysql://localhost:3306/mutualfund
spring.datasource.username=root
spring.datasource.password=root

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

management.endpoints.web.exposure.include=*

jwt.secret=MySuperSecureJWTSecretKey@2026



